-- USING INNER JOIN 5 TABLES
    SELECT STUDENTS.NAME,COURSES.COURSES,MENTORS.MENTORS,BATCHES.BATCHES FROM 
    students_list INNER JOIN students ON STUDENTS_LIST.ID=STUDENTS.SID
    INNER JOIN courses ON STUDENTS_LIST.CID=COURSES.CID
    INNER JOIN mentors ON STUDENTS_LIST.MID=MENTORS.MID
    INNER JOIN BATCHES ON STUDENTS_LIST.BID=BATCHES.BID;

CREATE TABLE STUDENTS_LIST(
    ID INT NOT NULL AUTO_INCREMENT,
    SID INT NOT NULL,
    CID INT NOT NULL,
    MID INT NOT NULL,
    BID INT NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO STUDENTS_LIST VALUES 
(NULL,1,1,1,1),
(NULL,2,1,2,2),
(NULL,3,1,3,3),
(NULL,4,2,4,4),
(NULL,5,2,1,1),
(NULL,6,2,2,2),
(NULL,7,2,3,3),
(NULL,8,3,4,4),
(NULL,9,3,1,1),
(NULL,10,3,2,2);

SELECT * FROM students_list


INSERT INTO STUDENTS VALUES 
(NULL,"DINESH","DINESH@GMAIL.COM","12734",1),
(NULL,"NISHA","NISHA@GMAIL.COM","12334",1),
(NULL,"NIVEDHIDHA","NIVEDHIDHA@GMAIL.COM","15234",1),
(NULL,"SACHIN","SACHIN@GMAIL.COM","12334",1),
(NULL,"AKASH","AKASH@GMAIL.COM","12`34",1),
(NULL,"PRIYA","PRIYA@GMAIL.COM","127634",1),
(NULL,"DHASWIN","DHASWIN@GMAIL.COM","19234",1),
(NULL,"ASWIN","ASWIN@GMAIL.COM","12234",1),
(NULL,"KAMAL","KAMAL@GMAIL.COM","12354",1),
(NULL,"DEEPAK","DEEPAK@GMAIL.COM","14234",1);